
package application.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdminService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:9010/admin?wsdl")
public class AdminService
    extends Service
{

    private final static URL ADMINSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADMINSERVICE_EXCEPTION;
    private final static QName ADMINSERVICE_QNAME = new QName("http://service/", "AdminService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9010/admin?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADMINSERVICE_WSDL_LOCATION = url;
        ADMINSERVICE_EXCEPTION = e;
    }

    public AdminService() {
        super(__getWsdlLocation(), ADMINSERVICE_QNAME);
    }

    public AdminService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADMINSERVICE_QNAME, features);
    }

    public AdminService(URL wsdlLocation) {
        super(wsdlLocation, ADMINSERVICE_QNAME);
    }

    public AdminService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADMINSERVICE_QNAME, features);
    }

    public AdminService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdminService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Admin
     */
    @WebEndpoint(name = "AdminPort")
    public Admin getAdminPort() {
        return super.getPort(new QName("http://service/", "AdminPort"), Admin.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Admin
     */
    @WebEndpoint(name = "AdminPort")
    public Admin getAdminPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "AdminPort"), Admin.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADMINSERVICE_EXCEPTION!= null) {
            throw ADMINSERVICE_EXCEPTION;
        }
        return ADMINSERVICE_WSDL_LOCATION;
    }

}
