
package application.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Login", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Login {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://service/", className = "application.stub.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service/", className = "application.stub.AddResponse")
    @Action(input = "http://service/Login/addRequest", output = "http://service/Login/addResponse")
    public void add(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns application.stub.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fingUserByUsername", targetNamespace = "http://service/", className = "application.stub.FingUserByUsername")
    @ResponseWrapper(localName = "fingUserByUsernameResponse", targetNamespace = "http://service/", className = "application.stub.FingUserByUsernameResponse")
    @Action(input = "http://service/Login/fingUserByUsernameRequest", output = "http://service/Login/fingUserByUsernameResponse")
    public User fingUserByUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
